version: "3.9"
services:
  server:
    build: ./BackEnd
    ports: 
      - "5000:5000"
    volumes:
      - ./BackEnd:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./FrontEnd/my-app
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd/my-app:/user/src/app
    depends_on:
    - server
